/**
 * Application-level enums (mirror Prisma enums)
 */

export enum WorkspaceRoleEnum {
  ADMIN = "ADMIN",
  MEMBER = "MEMBER",
}

export enum TaskStatusEnum {
  BACKLOG = "BACKLOG",
  TODO = "TODO",
  IN_PROGRESS = "IN_PROGRESS",
  IN_REVIEW = "IN_REVIEW",
  COMPLETED = "COMPLETED",
}

export enum TaskPriorityEnum {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum LeadStatusEnum {
  NEW = "NEW",
  CONTACTED = "CONTACTED",
  QUALIFIED = "QUALIFIED",
  NEGOTIATION = "NEGOTIATION",
  WON = "WON",
  LOST = "LOST",
}


export enum PaymentProviderEnum{
  STRIPE="STRIPE",
  RAZORPAY="RAZORPAY",
}


export enum PaymentStatusEnum{
  PENDING="PENDING",
  COMPLETED="COMPLETED",
  FAILED='FAILED',
  REFUNDED="REFUNDED",
}


export const ActivityAction = {
  USER_REGISTERED:         "USER_REGISTERED",
  LOGIN:                   "LOGIN",
  LOGOUT:                  "LOGOUT",
  LOGOUT_ALL_SESSIONS:     "LOGOUT_ALL_SESSIONS",
  EMAIL_VERIFIED:          "EMAIL_VERIFIED",
  PASSWORD_RESET:          "PASSWORD_RESET",
  PASSWORD_CHANGED:        "PASSWORD_CHANGED",
  SESSION_COMPROMISED:     "SESSION_COMPROMISED",
  SESSION_HIJACK_DETECTED: "SESSION_HIJACK_DETECTED",
  WORKSPACE_CREATED:       "WORKSPACE_CREATED",
  WORKSPACE_DELETED:       "WORKSPACE_DELETED",
  WORKSPACE_RESTORED:      "WORKSPACE_RESTORED",
  MEMBER_INVITED:          "MEMBER_INVITED",
  MEMBER_REMOVED:          "MEMBER_REMOVED",
  PROJECT_CREATED:         "PROJECT_CREATED",
  PROJECT_DELETED:         "PROJECT_DELETED",
  PROJECT_RESTORED:        "PROJECT_RESTORED",
  TASK_CREATED:            "TASK_CREATED",
  TASK_UPDATED:            "TASK_UPDATED",
  TASK_ASSIGNED:           "TASK_ASSIGNED",
  STATUS_CHANGE:           "STATUS_CHANGE",
  DELETE_TASK:             "DELETE_TASK",
  DEPENDENCY_ADDED:        "DEPENDENCY_ADDED",
  DEPENDENCY_REMOVED:      "DEPENDENCY_REMOVED",
  ATTACHMENT_UPLOADED:     "ATTACHMENT_UPLOADED",
  ATTACHMENT_DELETED:      "ATTACHMENT_DELETED",
  DEAL_CREATED:            "DEAL_CREATED",
  DEAL_UPDATED:            "DEAL_UPDATED",
  DEAL_DELETED:            "DEAL_DELETED",
  CONTACT_CREATED:         "CONTACT_CREATED",
  CONTACT_UPDATED:         "CONTACT_UPDATED",
  CONTACT_DELETED:         "CONTACT_DELETED",
  COMPANY_CREATED:         "COMPANY_CREATED",
  COMPANY_UPDATED:         "COMPANY_UPDATED",
  COMPANY_DELETED:         "COMPANY_DELETED",
  PAYMENT_COMPLETED:       "PAYMENT_COMPLETED",
  PAYMENT_FAILED:          "PAYMENT_FAILED",
} as const;

export type ActivityActionType = typeof ActivityAction[keyof typeof ActivityAction];